trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: project
    displayName: 'Project Name'
    type: string
    default: 'MeraStore.Shared.Kernel.Common.Core'
    values:
      - MeraStore.Shared.Kernel.Common.Core
      - MeraStore.Shared.Kernel.Common.Exceptions
      - MeraStore.Shared.Kernel.Caching
      - MeraStore.Shared.Kernel.Common.Http
      - MeraStore.Shared.Kernel.Common.Logging
      - MeraStore.Shared.Kernel.Common.WebApi
      - MeraStore.Shared.Kernel.Context
      - MeraStore.Shared.Kernel.Persistence

  - name: versionType
    displayName: 'Version Type'
    type: string
    default: 'None'
    values:
      - None  
      - New
      - Major
      - Minor
      - Build
      - Pre-Release

variables:
- group: nuget-pipeline-secrets

# Define other variables separately
- name: solution
  value: '**/*.sln'
- name: buildPlatform
  value: 'Any CPU'
- name: buildConfiguration
  value: 'Release'


jobs:
# - job: BuildAndTest
  # displayName: Restore and Build Project
  # variables:
    # packageVersion: '' # Placeholder for the calculated version
  # steps:
    # - task: DotNetCoreCLI@2
      # displayName: DotNet Restore
      # inputs:
        # command: 'restore'
        # projects: '**/${{ parameters.project }}.csproj'
        # feedsToUse: 'select'
        # vstsFeed: 'd3584f81-ddd5-413c-9dcc-8cf171921ad6/7548fa1b-58c8-45f0-9f9c-9a94233b60d3'
      # condition: succeeded()

    # - task: DotNetCoreCLI@2
      # displayName: DotNet Build
      # inputs:
        # command: 'build'
        # projects: '**/${{ parameters.project }}.csproj'
        # arguments: '--configuration $(buildConfiguration)'
      # condition: succeeded()

- job: CreateNugetPackage
  displayName: Create NuGet Package
  # dependsOn: BuildAndTest
  condition: ne('${{ parameters.versionType }}', 'None')
  variables:
    packageVersion: '' # Placeholder for the calculated version
  steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk'
      inputs:
        packageType: 'sdk'
        version: '9.0.x'

    - task: DotNetCoreCLI@2
      displayName: DotNet Restore
      inputs:
        command: 'restore'
        projects: '**/${{ parameters.project }}.csproj'
        feedsToUse: 'select'
        vstsFeed: 'd3584f81-ddd5-413c-9dcc-8cf171921ad6/7548fa1b-58c8-45f0-9f9c-9a94233b60d3'
      condition: succeeded()

    - script: |
        #!/bin/bash

        echo "Starting version calculation..."
        echo "Using the secret: $(System.AccessToken)"
        
        # Get version type from parameters
        versionType="${{ parameters.versionType }}"
        projectName="${{ parameters.project }}"

        echo "Version type selected: $versionType"
        echo "Project selected: $projectName"

        # Define package ID mapping as a Bash associative array
        declare -A packageIdMap=(
        ["MeraStore.Shared.Kernel.Common.Core"]="980c11e2-e72b-4f15-8c92-57d72efc9c99"
        ["MeraStore.Shared.Kernel.Common.Exceptions"]="e518e14e-e45c-4be2-ac37-fec0f79b0228"
        ["MeraStore.Shared.Kernel.Caching"]="23b33e91-2af0-47f3-8121-5130a8ec85d5"
        ["MeraStore.Shared.Kernel.Common.Http"]="71e4ee16-fb01-4983-9b8f-c4cfdd9ddc78"
        ["MeraStore.Shared.Kernel.Common.Logging"]="86070dcc-f2bb-421b-a3ca-b3c5371fa5df"
        ["MeraStore.Shared.Kernel.Common.WebApi"]="847345e2-2a60-46cf-b576-e9a66ce1bd4c"
        ["MeraStore.Shared.Kernel.Context"]="f0823a5b-bc23-4fd1-83ef-08c8afff00e7"
        ["MeraStore.Shared.Kernel.Persistence"]="564be5e3-a626-47d8-9951-6f68f4fe8cb3"
        )
        
        # Get package ID for the selected project
        packageId="${packageIdMap[$projectName]}"
        
        if [[ -z "$packageId" ]]; then
            echo "Error: Package ID for project '$projectName' not found."
            exit 1
        fi


        if [[ -z "$packageId" ]]; then
            echo "Error: Package ID for project '$projectName' not found."
            exit 1
        fi
        
        if [[ "$versionType" != "New" ]]; then
            ## Fetch the latest version from NuGet feed using the package ID
           
            nugetSource="https://feeds.dev.azure.com/merastore/d3584f81-ddd5-413c-9dcc-8cf171921ad6/_apis/Packaging/Feeds/7548fa1b-58c8-45f0-9f9c-9a94233b60d3/Packages/$packageId"

            echo "Fetching the latest version for package ID: $packageId from $nugetSource"
            

            response=$(curl -s -H "Authorization: Basic $AZURE_PATH" "$nugetSource")
            latestVersion=$(echo "$response" | jq -r '.versions[] | select(.isLatest==true) | .version')
            echo $latestVersion
            # Print the raw response for debugging
            echo "Raw response: $response"

            # Default to 1.0.0 if no latest version is found
            if [[ -z "$latestVersion" ]]; then
                latestVersion="1.0.0"
                echo "No latest version found. Defaulting to $latestVersion"
            else
                echo "Latest version found: $latestVersion"
            fi

            # Split the version into parts
            IFS='.' read -r majorVersion minorVersion buildNumber <<< "$latestVersion"
            echo "Current version parts - Major: $majorVersion, Minor: $minorVersion, Build: $buildNumber"

            preReleaseTag=""
            # Get current timestamp
            timestamp=$(date +%Y%m%d%H%M%S)

            # Determine version based on selected version type
            case "$versionType" in
                Major)
                    ((majorVersion++))
                    minorVersion=0
                    buildNumber=0
                    echo "Incrementing major version to $majorVersion, resetting minor and build to 0"
                    ;;
                Minor)
                    ((minorVersion++))
                    buildNumber=0
                    echo "Incrementing minor version to $minorVersion, resetting build to 0"
                    ;;
                Build)
                    ((buildNumber++))
                    echo "Incrementing build version to $buildNumber"
                    ;;
                Pre-Release)
                    ((buildNumber++))
                    preReleaseTag="-beta-$timestamp"
                    echo "Incrementing build version to $buildNumber and setting pre-release tag to $preReleaseTag"
                    ;;
            esac
        else
            # For 'New' version type
            majorVersion=1
            minorVersion=0
            buildNumber=0
            preReleaseTag=""
            echo "Creating new version: $majorVersion.$minorVersion.$buildNumber"
        fi

        # Construct the version string
        version="$majorVersion.$minorVersion.$buildNumber$preReleaseTag"
        echo "Final calculated version: $version"
        
        # Set the calculated version as a pipeline variable
        echo "##vso[task.setvariable variable=packageVersion]$version"
        echo "Version calculation completed."
        
        # Set the calculated version as a pipeline name
        echo "##vso[build.updatebuildnumber]$projectName-$version"
      displayName: 'Calculate Version Number'

    - task: DotNetCoreCLI@2
      displayName: DotNet Pack
      inputs:
        command: 'pack'
        packagesToPack: '**/${{ parameters.project }}.csproj'
        arguments: '--configuration $(buildConfiguration) /p:PackageVersion=$(packageVersion)'

    - task: DotNetCoreCLI@2
      displayName: DotNet Push
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
        nuGetFeedType: 'internal'
        publishVstsFeed: 'd3584f81-ddd5-413c-9dcc-8cf171921ad6/7548fa1b-58c8-45f0-9f9c-9a94233b60d3'
    
    - task: PublishBuildArtifacts@1
      displayName: Publish Artifacts
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        TargetPath: '\\${{ parameters.project }}\$(Build.DefinitionName)\$(Build.BuildNumber)'
        publishLocation: 'Container'
    
    - task: GitHubComment@0
      displayName: Comment
      inputs:
        gitHubConnection: 'GitHub - sanjyotagureddy'
        repositoryName: '$(Build.Repository.Name)'
        comment: 'Nuget: $(versionType), version: $(packageVersion) created'